library(magrittr)

family_survey <- surveymonkey::fetch_survey_obj(318058603) %>%
  surveymonkey::parse_survey()

family_survey_coalesced <- family_survey %>%
  dplyr::mutate(teacher = dplyr::coalesce(
    `Please select your child's teacher.`,
    `Please select your child's teacher. - Other (please specify)`,
    `Please select your child's teacher._2`,
    `Please select your child's teacher. - Other (please specify)_2`,
    `Please select your child's teacher._3`,
    `Please select your child's teacher. - Other (please specify)_3`,
    `Please select your child's teacher._4`,
    `Please select your child's teacher. - Other (please specify)_4`,
    `Please select your child's teacher._5`,
    `Please select your child's teacher. - Other (please specify)_5`,
    `Please select your child's teacher._6`,
    `Please select your child's teacher. - Other (please specify)_6`,
    `Please select your child's teacher._7`,
    `Please select your child's teacher. - Other (please specify)_7`,
    `Please select your child's teacher._8`,
    `Please select your child's teacher. - Other (please specify)_8`,
    `Please select your child's teacher._9`,
    `Please select your child's teacher. - Other (please specify)_9`,
    `Please select your child's teacher._10`,
    `Please select your child's teacher. - Other (please specify)_10`,
    `Please select your child's teacher._11`,
    `Please select your child's teacher. - Other (please specify)_11`,
    `Please select your child's teacher._12`,
    `Please select your child's teacher. - Other (please specify)_12`,
    `Please select your child's teacher._13`,
    `Please select your child's teacher. - Other (please specify)_13`,
    `Please select your child's teacher._14`,
    `Please select your child's teacher. - Other (please specify)_14`,
    `Please select your child's teacher._15`,
    `Please select your child's teacher. - Other (please specify)_15`,
    `Please select your child's teacher._16`,
    `Please select your child's teacher. - Other (please specify)_16`,
    `Please select your child's teacher._17`,
    `Please select your child's teacher. - Other (please specify)_17`,
    `Please select your child's teacher._18`,
    `Please select your child's teacher. - Other (please specify)_18`,
    `Please select your child's teacher._19`,
    `Please select your child's teacher. - Other (please specify)_19`,
    `Please select your child's teacher._20`,
    `Please select your child's teacher. - Other (please specify)_20`,
    `Please select your child's teacher._21`,
    `Please select your child's teacher. - Other (please specify)_21`,
    `Please select your child's teacher._22`,
    `Please select your child's teacher. - Other (please specify)_22`,
    `Please select your child's teacher._23`,
    `Please select your child's teacher. - Other (please specify)_23`,
    `Please select your child's teacher._24`,
    `Please select your child's teacher. - Other (please specify)_24`,
    `Please select your child's teacher._25`,
    `Please select your child's teacher. - Other (please specify)_25`,
    `Please select your child's teacher._26`,
    `Please select your child's teacher. - Other (please specify)_26`,
    `Please select your child's teacher._27`,
    `Please select your child's teacher. - Other (please specify)_27`,
    `Please select your child's teacher._28`,
    `Please select your child's teacher. - Other (please specify)_28`,
    `Please select your child's teacher._29`,
    `Please select your child's teacher. - Other (please specify)_29`,
    `Please select your child's teacher._30`,
    `Please select your child's teacher. - Other (please specify)_30`,
    `Please write in the name of your child's teacher.`
  )) %>%
  dplyr::select(-c(`Please select your child's teacher.`,
                   `Please select your child's teacher. - Other (please specify)`,
                   `Please select your child's teacher._2`,
                   `Please select your child's teacher. - Other (please specify)_2`,
                   `Please select your child's teacher._3`,
                   `Please select your child's teacher. - Other (please specify)_3`,
                   `Please select your child's teacher._4`,
                   `Please select your child's teacher. - Other (please specify)_4`,
                   `Please select your child's teacher._5`,
                   `Please select your child's teacher. - Other (please specify)_5`,
                   `Please select your child's teacher._6`,
                   `Please select your child's teacher. - Other (please specify)_6`,
                   `Please select your child's teacher._7`,
                   `Please select your child's teacher. - Other (please specify)_7`,
                   `Please select your child's teacher._8`,
                   `Please select your child's teacher. - Other (please specify)_8`,
                   `Please select your child's teacher._9`,
                   `Please select your child's teacher. - Other (please specify)_9`,
                   `Please select your child's teacher._10`,
                   `Please select your child's teacher. - Other (please specify)_10`,
                   `Please select your child's teacher._11`,
                   `Please select your child's teacher. - Other (please specify)_11`,
                   `Please select your child's teacher._12`,
                   `Please select your child's teacher. - Other (please specify)_12`,
                   `Please select your child's teacher._13`,
                   `Please select your child's teacher. - Other (please specify)_13`,
                   `Please select your child's teacher._14`,
                   `Please select your child's teacher. - Other (please specify)_14`,
                   `Please select your child's teacher._15`,
                   `Please select your child's teacher. - Other (please specify)_15`,
                   `Please select your child's teacher._16`,
                   `Please select your child's teacher. - Other (please specify)_16`,
                   `Please select your child's teacher._17`,
                   `Please select your child's teacher. - Other (please specify)_17`,
                   `Please select your child's teacher._18`,
                   `Please select your child's teacher. - Other (please specify)_18`,
                   `Please select your child's teacher._19`,
                   `Please select your child's teacher. - Other (please specify)_19`,
                   `Please select your child's teacher._20`,
                   `Please select your child's teacher. - Other (please specify)_20`,
                   `Please select your child's teacher._21`,
                   `Please select your child's teacher. - Other (please specify)_21`,
                   `Please select your child's teacher._22`,
                   `Please select your child's teacher. - Other (please specify)_22`,
                   `Please select your child's teacher._23`,
                   `Please select your child's teacher. - Other (please specify)_23`,
                   `Please select your child's teacher._24`,
                   `Please select your child's teacher. - Other (please specify)_24`,
                   `Please select your child's teacher._25`,
                   `Please select your child's teacher. - Other (please specify)_25`,
                   `Please select your child's teacher._26`,
                   `Please select your child's teacher. - Other (please specify)_26`,
                   `Please select your child's teacher._27`,
                   `Please select your child's teacher. - Other (please specify)_27`,
                   `Please select your child's teacher._28`,
                   `Please select your child's teacher. - Other (please specify)_28`,
                   `Please select your child's teacher._29`,
                   `Please select your child's teacher. - Other (please specify)_29`,
                   `Please select your child's teacher._30`,
                   `Please select your child's teacher. - Other (please specify)_30`,
                   `Please write in the name of your child's teacher.`))

readr::write_rds(family_survey_coalesced, here::here("data/family_survey.rds"))
