library(magrittr)

student_survey <- surveymonkey::fetch_survey_obj(312653807) %>%
  surveymonkey::parse_survey()

student_survey_coalesced <- student_survey %>%
  dplyr::mutate(teacher = dplyr::coalesce(
    `Please select your teacher.`,
    `Please select your teacher. - Other (please specify)`,
    `Please select your teacher._2`,
    `Please select your teacher. - Other (please specify)_2`,
    `Please select your teacher._3`,
    `Please select your teacher. - Other (please specify)_3`,
    `Please select your teacher._4`,
    `Please select your teacher. - Other (please specify)_4`,
    `Please select your teacher._5`,
    `Please select your teacher. - Other (please specify)_5`,
    `Please select your teacher._6`,
    `Please select your teacher. - Other (please specify)_6`,
    `Please select your teacher._7`,
    `Please select your teacher. - Other (please specify)_7`,
    `Please select your teacher._8`,
    `Please select your teacher. - Other (please specify)_8`,
    `Please select your teacher._9`,
    `Please select your teacher. - Other (please specify)_9`,
    `Please select your teacher._10`,
    `Please select your teacher. - Other (please specify)_10`,
    `Please select your teacher._11`,
    `Please select your teacher. - Other (please specify)_11`,
    `Please select your teacher._12`,
    `Please select your teacher. - Other (please specify)_12`,
    `Please select your teacher._13`,
    `Please select your teacher. - Other (please specify)_13`,
    `Please select your teacher._14`,
    `Please select your teacher. - Other (please specify)_14`,
    `Please select your teacher._15`,
    `Please select your teacher. - Other (please specify)_15`,
    `Please select your teacher._16`,
    `Please select your teacher. - Other (please specify)_16`,
    `Please select your teacher._17`,
    `Please select your teacher. - Other (please specify)_17`,
    `Please select your teacher._18`,
    `Please select your teacher. - Other (please specify)_18`,
    `Please select your teacher._19`,
    `Please select your teacher. - Other (please specify)_19`,
    `Please select your teacher._20`,
    `Please select your teacher. - Other (please specify)_20`,
    `Please select your teacher._21`,
    `Please select your teacher. - Other (please specify)_21`,
    `Please select your teacher._22`,
    `Please select your teacher. - Other (please specify)_22`,
    `Please select your teacher._23`,
    `Please select your teacher. - Other (please specify)_23`,
    `Please select your teacher._24`,
    `Please select your teacher. - Other (please specify)_24`,
    `Please select your teacher._25`,
    `Please select your teacher. - Other (please specify)_25`,
    `Please select your teacher._26`,
    `Please select your teacher. - Other (please specify)_26`,
    `Please select your teacher._27`,
    `Please select your teacher. - Other (please specify)_27`,
    `Please select your teacher._28`,
    `Please select your teacher. - Other (please specify)_28`,
    `Please select your teacher._29`,
    `Please select your teacher. - Other (please specify)_29`,
    `Please select your teacher._30`,
    `Please select your teacher. - Other (please specify)_30`
  )) %>%
  dplyr::select(-c(`Please select your teacher.`,
            `Please select your teacher. - Other (please specify)`,
            `Please select your teacher._2`,
            `Please select your teacher. - Other (please specify)_2`,
            `Please select your teacher._3`,
            `Please select your teacher. - Other (please specify)_3`,
            `Please select your teacher._4`,
            `Please select your teacher. - Other (please specify)_4`,
            `Please select your teacher._5`,
            `Please select your teacher. - Other (please specify)_5`,
            `Please select your teacher._6`,
            `Please select your teacher. - Other (please specify)_6`,
            `Please select your teacher._7`,
            `Please select your teacher. - Other (please specify)_7`,
            `Please select your teacher._8`,
            `Please select your teacher. - Other (please specify)_8`,
            `Please select your teacher._9`,
            `Please select your teacher. - Other (please specify)_9`,
            `Please select your teacher._10`,
            `Please select your teacher. - Other (please specify)_10`,
            `Please select your teacher._11`,
            `Please select your teacher. - Other (please specify)_11`,
            `Please select your teacher._12`,
            `Please select your teacher. - Other (please specify)_12`,
            `Please select your teacher._13`,
            `Please select your teacher. - Other (please specify)_13`,
            `Please select your teacher._14`,
            `Please select your teacher. - Other (please specify)_14`,
            `Please select your teacher._15`,
            `Please select your teacher. - Other (please specify)_15`,
            `Please select your teacher._16`,
            `Please select your teacher. - Other (please specify)_16`,
            `Please select your teacher._17`,
            `Please select your teacher. - Other (please specify)_17`,
            `Please select your teacher._18`,
            `Please select your teacher. - Other (please specify)_18`,
            `Please select your teacher._19`,
            `Please select your teacher. - Other (please specify)_19`,
            `Please select your teacher._20`,
            `Please select your teacher. - Other (please specify)_20`,
            `Please select your teacher._21`,
            `Please select your teacher. - Other (please specify)_21`,
            `Please select your teacher._22`,
            `Please select your teacher. - Other (please specify)_22`,
            `Please select your teacher._23`,
            `Please select your teacher. - Other (please specify)_23`,
            `Please select your teacher._24`,
            `Please select your teacher. - Other (please specify)_24`,
            `Please select your teacher._25`,
            `Please select your teacher. - Other (please specify)_25`,
            `Please select your teacher._26`,
            `Please select your teacher. - Other (please specify)_26`,
            `Please select your teacher._27`,
            `Please select your teacher. - Other (please specify)_27`,
            `Please select your teacher._28`,
            `Please select your teacher. - Other (please specify)_28`,
            `Please select your teacher._29`,
            `Please select your teacher. - Other (please specify)_29`,
            `Please select your teacher._30`,
            `Please select your teacher. - Other (please specify)_30`))

readr::write_rds(student_survey_coalesced, here::here("data/student_survey.rds"))
