---
title: "Data Load for Knowledge Assessment"
author: "Duncan Gates"
date: "10/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(surveymonkey)
library(TeachingLab)
library(ggtext)
#### Reminder to go back to Survey 14 ####
```

## Get Data and Write to Dashboard data folder

```{r}
options(sm_oauth_token = "wD.rd9HKenA2QV2Z2zV.kJwL7533YR3TcbP0Ii7--tHadLRlID-hv5Kz8oAVvHsKXUSn9KRnzz31DcKqb8vcLMqjuHjYz7r3vW7kQj3TZ3oboSG5mvxi5ZijlFhL8ylm")

# surveys <- surveymonkey::browse_surveys()
ids_surveys <- tibble::tibble(
  title = c("ELA: Guidebooks Diverse Learners Bootcamp - Teacher",
            "ELA: CRSE PLC", "Math: Cycle of Inquiry V- Sequencing and Connecting Representations",
            "ELA: Bootcamp - Foundational Skills Bootcamp Skills (K-2)",
            "ELA: Guidebooks Diverse Learners Bootcamp Writing", "Math: Bootcamp",
            "ELA: Bootcamp - General", "Math: Cycle of Inquiry I - Eliciting Student Thinking",
            "ELA: Guidebooks Diverse Learners Bootcamp - Leader", "School Leaders: ELA",
            "Math: Bootcamp - EIC", "Math: Accelerating Learning", "ELA: HQIM & Enrichment",
            "ELA General: Cycle of Inquiry - Complex Text", "ELA: Guidebooks Diverse Learners Cycle of Inquiry - Vocabulary",
            "ELA: Guidebooks Diverse Learners Cycle of Inquiry - Fluency",
            "ELA: Guidebooks Cycle of Inquiry 1", "ELA: Guidebooks Cycle of Inquiry 2"),
  id = c("310008951", "312484554", "311404789", "309842602",
         "310775522", "309842333", "309800566", "311433379", "311069987",
         "312485414", "309893890", "310768681", "310009771", "311404498",
         "310776879", "310776199", "310778066", "310777524")
) %>%
  dplyr::mutate(count = dplyr::row_number())

fetch_survey_2 <- function(id, name) {
  #### Get survey object ####
  survey <- surveymonkey::fetch_survey_obj(id = id)
  #### Parse survey ####
  survey_parsed <- survey %>%
    surveymonkey::parse_survey()
  #### Assign all to environment with format surveyname ####
  assign(value = survey_parsed, x = paste0("survey", name), envir = .GlobalEnv)
  #### Compile dataframe of all the surveys new names and add ####
  name_df <- tibble::tibble(names = paste0("survey", name)) %>%
    dplyr::mutate(count = name) %>%
    dplyr::left_join(ids_surveys, by = "count") %>%
    dplyr::mutate(title = stringr::str_replace_all(title, " ", "")) %>%
    dplyr::mutate(title = stringr::str_replace_all(title, ":", ""))
  print(name_df)
  #### Write to data folder with original name####
  purrr::map2(.x = name_df$names, .y = name_df$title, ~ readr::write_rds(x = get(.x), file = paste0(here::here("Dashboards/KnowledgeAssessments/data/"), .y, ".rds")))
}

purrr::map2(.x = ids_surveys$id, .y = ids_surveys$count, ~ fetch_survey_2(id = .x, name = .y))
```

## ELA

```{r eval = F}
#### Survey 1: ELA General Bootcamp ####
ela_general_bootcamp <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/ELABootcamp-General.rds")) %>%
  group_by(respondent_id) %>%
  summarise_all(coalesce_by_column) %>%
  mutate(id = paste0(str_to_lower(`Please write in your 3 initials. If you do not have a middle initial, please write X.<br>(This is used to link pre/post assessments, but is kept confidential.)`), `Please write in your four-digit birthday (MMDD).<br>(This is used to pre/post link assessments, but is kept confidential.)`)) %>%
  group_by(id) %>%
  mutate(n_response = n(),
         maxdate = max(date_created),
         prepost = if_else(n_response > 1 & maxdate == date_created, "post", "pre"))
# ela_general_bootcamp <- readr::read_rds("data/ELABootcamp-General.rds")

ela_general_bootcamp_correct <- tibble::tibble(question = c("Which of the following are literacy instructional shifts? Select all that apply. - Regular practice with complex texts and their academic language.", 
                                                            "Which of the following are literacy instructional shifts? Select all that apply. - Building knowledge through content-rich non-fiction.", 
                                                            "Which of the following are literacy instructional shifts? Select all that apply. - Equal balance of text-based writing and writing from personal experiences.", 
                                                            "Which of the following are literacy instructional shifts? Select all that apply. - Regular opportunities for direct instruction on reading comprehension strategies.", 
                                                            "When designing literacy lessons, teachers should start with which of the following?", 
                                                            "When designing literacy lessons, teachers should start with which of the following?", 
                                                            "When designing literacy lessons, teachers should start with which of the following?", 
                                                            "When designing literacy lessons, teachers should start with which of the following?", 
                                                            "Which of the following is the single biggest differentiator of college and career-readiness?", 
                                                            "Which of the following is the single biggest differentiator of college and career-readiness?", 
                                                            "Which of the following is the single biggest differentiator of college and career-readiness?", 
                                                            "Which of the following is the single biggest differentiator of college and career-readiness?", 
                                                            "Which of the following approaches for selecting texts for whole-class reading instruction are aligned with post-shifts literacy instruction? Select all that apply. - Selecting a text that is at or above the grade-level complexity.", 
                                                            "Which of the following approaches for selecting texts for whole-class reading instruction are aligned with post-shifts literacy instruction? Select all that apply. - Selecting a text that is rich in meaning.", 
                                                            "Which of the following approaches for selecting texts for whole-class reading instruction are aligned with post-shifts literacy instruction? Select all that apply. - Selecting an adapted version of the main text for below-grade-level readers.", 
                                                            "Which of the following approaches for selecting texts for whole-class reading instruction are aligned with post-shifts literacy instruction? Select all that apply. - Selecting a text for the class based on student interest.", 
                                                            "Which of the following describe strategies for supporting struggling readers? Select all that apply. - Read the complex text aloud for students.", 
                                                            "Which of the following describe strategies for supporting struggling readers? Select all that apply. - Read aloud a simple article to build knowledge of the topic while students follow along.", 
                                                            "Which of the following describe strategies for supporting struggling readers? Select all that apply. - Have students read the full text multiple times to find the main idea.", 
                                                            "Which of the following describe strategies for supporting struggling readers? Select all that apply. - Ask simpler questions about the same text."),
                                                  coding = c("Regular practice with complex texts and their academic language.",
                                                             "Building knowledge through content-rich non-fiction.", 
                                                             "Equal balance of text-based writing and writing from personal experiences.",
                                                             "Regular opportunities for direct instruction on reading comprehension strategies.",
                                                             "A complex text that is worthy of reading multiple times.",
                                                             "A strategy they want students to implement (main idea, predicting, etc.).",
                                                             "A standard (identify author’s purpose).",
                                                             "I’m not sure.",
                                                             "Ability to read fluently and accurately.",
                                                             "Ability to read and write at grade-level independently.",
                                                             "Ability to read complex text independently and proficiently.",
                                                             "I’m not sure.",
                                                             "Selecting a text that is at or above the grade-level complexity.",
                                                             "Selecting a text that is rich in meaning.",
                                                             "Selecting an adapted version of the main text for below-grade-level readers.",
                                                             "Selecting a text for the class based on student interest.",
                                                             "Read the complex text aloud for students.",
                                                             "Read aloud a simple article to build knowledge of the topic while students follow along.",
                                                             "Have students read the full text multiple times to find the main idea.",
                                                             "Ask simpler questions about the same text."))
ela_general_bootcamp_percent <- purrr::map2_df(ela_general_bootcamp_correct$question, 
                                        ela_general_bootcamp_correct$coding, ~ TeachingLab::score_question(data = ela_general_bootcamp, 
                                                                                              question = .x,
                                                                                              coding = .y,
                                                                                              grouping = `Please select your site (district, parish, network, or school)`))
```

# Plot Template

```{r}
correct <- c("Regular practice with complex texts and their academic language.",
             "Building knowledge through content-rich non-fiction.",
             "A complex text that is worthy of reading multiple times.",
             "Ability to read complex text independently and proficiently.",
             "Selecting a text that is at or above the grade-level complexity.",
             "Selecting a text that is rich in meaning.",
             "Read the complex text aloud for students.",
             "Read aloud a simple article to build knowledge of the topic while students follow along.")
ela_general_plot <- ela_general_bootcamp_percent %>%
  mutate(question = str_remove_all(str_remove_all(question, "(?<=\\s-\\s).*| - "), " - ")) %>%
  group_by(question, `Please select your site (district, parish, network, or school)`) %>%
  summarise(percent = if_else(percent == 100, 100*(n/max(n)), percent),
            answer = unlist(answer))

ela_general_plot %>%
  mutate(answer = TeachingLab::html_wrap(answer, n = 30),
         answer = if_else(str_replace_all(answer, "<br>", " ") %in% correct, 
                          paste0("<b style='color:#04abeb'>", answer, "</b>"), 
                          answer),
         question = TeachingLab::html_wrap(question, n = 30)) %>%
  filter(`Please select your site (district, parish, network, or school)` == "NYC District 11 -  IS 326, NY") %>%
  ggplot(aes(fct_reorder(answer, percent), percent, fill = percent)) +
  geom_col(width = 0.25) +
  geom_text(aes(label = paste0(round(percent), "%")), hjust = -0.2) +
  facet_wrap( ~ question, scales = "free") +
  coord_flip() +
  scale_fill_continuous() +
  labs(x = "", y = "", caption = "*Correct answers are in bold",
       title = "% Answering Each Item in ELA Bootcamp General") +
  scale_y_continuous(labels = scales::label_percent(scale = 1), expand = c(0.14, 0)) +
  theme_tl() +
  theme(axis.text.y = element_markdown(),
        strip.text = element_markdown(hjust = 0.5, face = "bold"),
        plot.title = element_text(face = "bold"))
ggsave(here::here("Images/KnowledgeAssessments/example1.png"), width = 15, height = 10)
```


```{r eval = F}
#### Making Survey 2 ELA General Cycle of Inquiry ####
#### Not complete as of 10-29-31, will need updating on questions, answers ####
# ela_cycle_of_inquiry <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/ELAGeneralCycleofInquiry-ComplexText.rds"))
ela_cycle_of_inquiry <- readr::read_rds("data/ELAGeneralCycleofInquiry-ComplexText.rds")

ela_cycle_of_inquiry_correct <- tibble::tibble(question = c("For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Print concepts", 
                                               "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Phonological awareness", 
                                               "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Vocabulary development", 
                                               "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Fluency", 
                                               "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Reading comprehension", 
                                               "A structured phonics program is important in K-2 for the following reasons EXCEPT:", 
                                               "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Utilize a variety of ongoing assessment data to determine the focus of instruction for small groups", 
                                               "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Group students by their ongoing phase of development with regard to the foundational skills", 
                                               "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Only provide foundational skills instruction during small group time", 
                                               "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Adhere to a same structure of number of groups and members of groups for the entirety of the year"),
                                  coding = c("Print Concepts", "Phonological awareness", "incorrect", "Fluency", "incorrect",
                                             "It prompts students to use context clues and pictures to decode words",
                                             "Utilize a variety of ongoing assessment data to determine the focus of instruction for small groups",
                                             "Group students by their ongoing phase of development with regard to the foundational skills",
                                             "incorrect",
                                             "incorrect"))
ela_cycle_of_inquiry_percent <- purrr::map2_df(ela_cycle_of_inquiry_correct$question, 
                                               ela_cycle_of_inquiry_correct$coding, ~ TeachingLab::score_question(data = ela_cycle_of_inquiry, 
                                                                                              question = .x,
                                                                                              coding = .y,
                                                                                              grouping = "Please select your site (district, parish, network, or school)"))
```


```{r}
#### Making Survey 3 ELA Foundational Skills Bootcamp ####
# ela_foundational_skills <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/ELABootcamp-FoundationalSkillsBootcampSkills(K-2).rds"))
ela_foundational_skills <- readr::read_rds("data/ELABootcamp-FoundationalSkillsBootcampSkills(K-2).rds")

ela_foundational_skills_correct <- tibble::tibble(question = c("For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Print concepts", 
                                                               "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Phonological awareness", 
                                                               "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Vocabulary development", 
                                                               "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Fluency", 
                                                               "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Reading comprehension", 
                                                               "A structured phonics program is important in K-2 for the following reasons EXCEPT:", 
                                                               "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Utilize a variety of ongoing assessment data to determine the focus of instruction for small groups", 
                                                               "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Group students by their ongoing phase of development with regard to the foundational skills", 
                                                               "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Only provide foundational skills instruction during small group time", 
                                                               "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Adhere to a same structure of number of groups and members of groups for the entirety of the year"),
                                                  coding = c("Print Concepts", "Phonological awareness", "incorrect", "Fluency", "incorrect",
                                                             "It prompts students to use context clues and pictures to decode words",
                                                             "Utilize a variety of ongoing assessment data to determine the focus of instruction for small groups",
                                                             "Group students by their ongoing phase of development with regard to the foundational skills",
                                                             "incorrect",
                                                             "incorrect"))
ela_foundational_skills_percent <- purrr::map2_df(ela_foundational_skills_correct$question, 
                                                  ela_foundational_skills_correct$coding, ~ TeachingLab::score_question(data = ela_foundational_skills, 
                                                                                                                        question = .x,
                                                                                                                        coding = .y,
                                                                                                                        grouping = "Please select your site (district, parish, network, or school)"))
```

```{r eval = F}
#### Making Survey 4 ELA Guidebooks Cycle of Inquiry 1 ####
#### Not complete as of 10-29-31, will need updating on questions, answers ####
# ela_guidebooks_cycle1 <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/ELAGuidebooksCycleofInquiry1.rds"))
ela_guidebooks_cycle1 <- readr::read_rds("data/ELAGuidebooksCycleofInquiry1.rds")

ela_guidebooks_cycle1_correct <- tibble::tibble(question = c("For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Print concepts", 
                                                               "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Phonological awareness", 
                                                               "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Vocabulary development", 
                                                               "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Fluency", 
                                                               "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Reading comprehension", 
                                                               "A structured phonics program is important in K-2 for the following reasons EXCEPT:", 
                                                               "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Utilize a variety of ongoing assessment data to determine the focus of instruction for small groups", 
                                                               "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Group students by their ongoing phase of development with regard to the foundational skills", 
                                                               "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Only provide foundational skills instruction during small group time", 
                                                               "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Adhere to a same structure of number of groups and members of groups for the entirety of the year"),
                                                  coding = c("Print Concepts", "Phonological awareness", "incorrect", "Fluency", "incorrect",
                                                             "It prompts students to use context clues and pictures to decode words",
                                                             "Utilize a variety of ongoing assessment data to determine the focus of instruction for small groups",
                                                             "Group students by their ongoing phase of development with regard to the foundational skills",
                                                             "incorrect",
                                                             "incorrect"))
ela_guidebooks_cycle1_percent <- purrr::map2_df(ela_guidebooks_cycle1_correct$question, 
                                                ela_guidebooks_cycle1_correct$coding, ~ TeachingLab::score_question(data = ela_guidebooks_cycle1, 
                                                                                                                        question = .x,
                                                                                                                        coding = .y,
                                                                                                                        grouping = "Please select your site (district, parish, network, or school)"))
```

```{r eval = F}
#### Making Survey 5 ELA Guidebooks Cycle of Inquiry 2 ####
#### Not complete as of 10-29-31, will need updating on questions, answers ####
# ela_guidebooks_cycle2 <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/ELAGuidebooksCycleofInquiry2.rds"))
ela_guidebooks_cycle2 <- readr::read_rds("data/ELAGuidebooksCycleofInquiry2.rds")

ela_guidebooks_cycle2_correct <- tibble::tibble(question = c("For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Print concepts", 
                                                             "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Phonological awareness", 
                                                             "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Vocabulary development", 
                                                             "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Fluency", 
                                                             "For each of the following, indicate if it is a component of the foundational skills of reading. Select all that apply. - Reading comprehension", 
                                                             "A structured phonics program is important in K-2 for the following reasons EXCEPT:", 
                                                             "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Utilize a variety of ongoing assessment data to determine the focus of instruction for small groups", 
                                                             "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Group students by their ongoing phase of development with regard to the foundational skills", 
                                                             "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Only provide foundational skills instruction during small group time", 
                                                             "When planning for differentiated small group instruction to support the foundational skills, which of the following should teachers engage in? Select all that apply. - Adhere to a same structure of number of groups and members of groups for the entirety of the year"),
                                                coding = c("Print Concepts", "Phonological awareness", "incorrect", "Fluency", "incorrect",
                                                           "It prompts students to use context clues and pictures to decode words",
                                                           "Utilize a variety of ongoing assessment data to determine the focus of instruction for small groups",
                                                           "Group students by their ongoing phase of development with regard to the foundational skills",
                                                           "incorrect",
                                                           "incorrect"))
ela_guidebooks_cycle2_percent <- purrr::map2_df(ela_guidebooks_cycle2_correct$question, 
                                                ela_guidebooks_cycle2_correct$coding, ~ TeachingLab::score_question(data = ela_guidebooks_cycle2, 
                                                                                                                    question = .x,
                                                                                                                    coding = .y,
                                                                                                                    grouping = "Please select your site (district, parish, network, or school)"))
```


```{r}
#### Making Survey 6 ELA Guidebooks Diverse Learners: Bootcamp - Leader ####
# ela_guidebooks_diverse_learners_leader <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/ELAGuidebooksDiverseLearnersBootcamp-Leader.rds"))
ela_guidebooks_diverse_learners_leader <- readr::read_rds("data/ELAGuidebooksDiverseLearnersBootcamp-Leader.rds")

ela_guidebooks_diverse_learners_leader_correct <- tibble::tibble(
  question = c("Which of the following are true about the Diverse Learners Planning Guide’s approach to supporting diverse learners? Select all that apply. - Some students need targeted additional support outside of their ELA block.", 
               "Which of the following are true about the Diverse Learners Planning Guide’s approach to supporting diverse learners? Select all that apply. - Students who need it should have practice with the text before they engage with that text in their ELA block.", 
               "Which of the following are true about the Diverse Learners Planning Guide’s approach to supporting diverse learners? Select all that apply. - Students who need it should be front-loaded with reading comprehension strategies before engaging with a complex grade-level text.", 
               "Which of the following are true about the Diverse Learners Planning Guide’s approach to supporting diverse learners? Select all that apply. - Students need to build up all general basic skills before they can take part in Tier 1 instruction.", 
               "Through observing her students, Mrs. Richards concluded that eight of her students may not know the elements of a written response. There is a culminating writing task that all students will need to complete next week. How can she BEST plan to support these eight students so that they will be successful on this writing task?"),
  coding = c("Some students need targeted additional support outside of their ELA block.",
             "Students who need it should have practice with the text before they engage with that text in their ELA block.",
             "incorrect",
             "incorrect",
             "Plan with the interventionist, Mr. Liu, to have the students work with him to analyze some exemplar written responses for key elements a few days before the writing task is assigned."))

ela_guidebooks_diverse_learners_leader_percent <- purrr::map2_df(ela_guidebooks_diverse_learners_leader_correct$question, 
                                                                 ela_guidebooks_diverse_learners_leader_correct$coding, ~ TeachingLab::score_question(data = ela_guidebooks_diverse_learners_leader, 
                                                                                                                    question = .x,
                                                                                                                    coding = .y,
                                                                                                                    grouping = "Please select your site (district, parish, network, or school)."))
```

```{r}
#### Making Survey 7 ELA Guidebooks Diverse Learners: Bootcamp - Teacher ####
# ela_guidebooks_diverse_learners_teacher <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/ELAGuidebooksDiverseLearnersBootcamp-Teacher.rds"))
ela_guidebooks_diverse_learners_teacher <- readr::read_rds("data/ELAGuidebooksDiverseLearnersBootcamp-Teacher.rds")

ela_guidebooks_diverse_learners_teacher_correct <- tibble::tibble(
  question = c("Which of the following are true about the Diverse Learners Planning Guide’s approach to supporting diverse learners? Select all that apply. - Some students need targeted additional support outside of their ELA block.", 
               "Which of the following are true about the Diverse Learners Planning Guide’s approach to supporting diverse learners? Select all that apply. - Students who need it should have practice with the text before they engage with that text in their ELA block.", 
               "Which of the following are true about the Diverse Learners Planning Guide’s approach to supporting diverse learners? Select all that apply. - Students who need it should be front-loaded with reading comprehension strategies before engaging with a complex grade-level text.", 
               "Which of the following are true about the Diverse Learners Planning Guide’s approach to supporting diverse learners? Select all that apply. - Students need to build up all general basic skills before they can take part in Tier 1 instruction.", 
               "Through observing her students, Mrs. Richards concluded that eight of her students may not know the elements of a written response. There is a culminating writing task that all students will need to complete next week. How can she BEST plan to support these eight students so that they will be successful on this writing task?", 
               "Which of the following observations describe practices for establishing an inclusive and student centered classroom culture? Select all that apply. - Students nominate a set of discussion agreements to use in their class.", 
               "Which of the following observations describe practices for establishing an inclusive and student centered classroom culture? Select all that apply. - The teacher holds a mediation conversation for two students after witnessing one student making a derogatory comment toward the other.", 
               "Which of the following observations describe practices for establishing an inclusive and student centered classroom culture? Select all that apply. - Students research one of three 19th century American heroes: Abraham Lincoln, Thomas Edison, and Mark Twain.", 
               "Which of the following observations describe practices for establishing an inclusive and student centered classroom culture? Select all that apply. - A classroom norm is that “All students must make at least one comment during a class discussion.”", 
               "What is the ideal use case of the Diverse Learners Planning Guide?"),
  coding = c("Some students need targeted additional support outside of their ELA block.",
             "Students who need it should have practice with the text before they engage with that text in their ELA block.",
             "incorrect",
             "incorrect",
             "Plan with the interventionist, Mr. Liu, to have the students work with him to analyze some exemplar written responses for key elements a few days before the writing task is assigned.",
             "Students nominate a set of discussion agreements to use in their class.",
             "The teacher holds a mediation conversation for two students after witnessing one student making a derogatory comment toward the other.",
             "incorrect",
             "incorrect",
             "To help teachers plan to use the supports and allow for students to preview the skills that diverse learners might need to engage with grade-level texts and tasks ahead of whole-class instruction."))

ela_guidebooks_diverse_learners_teacher_percent <- purrr::map2_df(ela_guidebooks_diverse_learners_teacher_correct$question, 
                                                                 ela_guidebooks_diverse_learners_teacher_correct$coding, ~ TeachingLab::score_question(data = ela_guidebooks_diverse_learners_teacher, 
                                                                                                                                                      question = .x,
                                                                                                                                                      coding = .y,
                                                                                                                                                      grouping = "Please select your site (district, parish, network, or school)."))
```


```{r}
#### Making Survey 8 ELA Guidebooks Diverse Learners: Bootcamp - Writing ####
# ela_guidebooks_diverse_learners_writing <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/ELAGuidebooksDiverseLearnersBootcampWriting.rds"))
ela_guidebooks_diverse_learners_writing <- readr::read_rds("data/ELAGuidebooksDiverseLearnersBootcampWriting.rds")

ela_guidebooks_diverse_learners_writing_correct <- tibble::tibble(
  question = c("Which of the following are true about how most students become better writers? Select all that apply. - Students need to be explicitly taught how to write.", 
               "Which of the following are true about how most students become better writers? Select all that apply. - Students should  plan out what they’re going to write before beginning to write.", 
               "Which of the following are true about how most students become better writers? Select all that apply. - Students can become good writers by reading complex texts.", 
               "Which of the following are true about how most students become better writers? Select all that apply. - Students should have isolated grammar lessons so that they can apply grammar rules in their writing.", 
               "Which of the following are true about how most students become better writers? Select all that apply. - I’m not sure", 
               "All of the following are effective ways a teacher can help students write a stronger sentence EXCEPT:"),
  coding = c("Students need to be explicitly taught how to write.",
             "Students should  plan out what they’re going to write before beginning to write.",
             "incorrect",
             "incorrect",
             "incorrect",
             "Identify incorrect uses of punctuation and correct them."))

ela_guidebooks_diverse_learners_writing_percent <- purrr::map2_df(ela_guidebooks_diverse_learners_writing_correct$question, 
                                                                  ela_guidebooks_diverse_learners_writing_correct$coding, ~ TeachingLab::score_question(data = ela_guidebooks_diverse_learners_writing, 
                                                                                                                                                        question = .x,
                                                                                                                                                        coding = .y,
                                                                                                                                                        grouping = "Please select your site (district, parish, network, or school)"))
```

```{r eval = F}
#### Making Survey 9 ELA Guidebooks Diverse Learners: Bootcamp - Fluency ####
#### Not complete as of 10-29-31, will need updating on questions, answers ####
# ela_guidebooks_diverse_learners_fluency <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/ELAGuidebooksDiverseLearnersCycleofInquiry-Fluency.rds"))
ela_guidebooks_diverse_learners_fluency <- readr::read_rds("data/ELAGuidebooksDiverseLearnersCycleofInquiry-Fluency.rds")

ela_guidebooks_diverse_learners_fluency_correct <- tibble::tibble(
  question = c("Which of the following are true about how most students become better writers? Select all that apply. - Students need to be explicitly taught how to write.", 
               "Which of the following are true about how most students become better writers? Select all that apply. - Students should  plan out what they’re going to write before beginning to write.", 
               "Which of the following are true about how most students become better writers? Select all that apply. - Students can become good writers by reading complex texts.", 
               "Which of the following are true about how most students become better writers? Select all that apply. - Students should have isolated grammar lessons so that they can apply grammar rules in their writing.", 
               "Which of the following are true about how most students become better writers? Select all that apply. - I’m not sure", 
               "All of the following are effective ways a teacher can help students write a stronger sentence EXCEPT:"),
  coding = c("Students need to be explicitly taught how to write.",
             "Students should  plan out what they’re going to write before beginning to write.",
             "incorrect",
             "incorrect",
             "incorrect",
             "Identify incorrect uses of punctuation and correct them."))

ela_guidebooks_diverse_learners_fluency_percent <- purrr::map2_df(ela_guidebooks_diverse_learners_fluency_correct$question, 
                                                                  ela_guidebooks_diverse_learners_fluency_correct$coding, ~ TeachingLab::score_question(data = ela_guidebooks_diverse_learners_fluency, 
                                                                                                                                                        question = .x,
                                                                                                                                                        coding = .y,
                                                                                                                                                        grouping = "Please select your site (district, parish, network, or school)"))
```

```{r eval = F}
#### Making Survey 10 ELA Guidebooks Diverse Learners: Vocabulary  ####
#### Not complete as of 10-29-31, will need updating on questions, answers ####
ela_guidebooks_diverse_learners_vocabulary <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/ELAGuidebooksDiverseLearnersCycleofInquiry-Vocabulary.rds"))
ela_guidebooks_diverse_learners_vocabulary <- readr::read_rds("data/ELAGuidebooksDiverseLearnersCycleofInquiry-Vocabulary.rds")

ela_guidebooks_diverse_learners_vocabulary_correct <- tibble::tibble(
  question = c("Which of the following are true about how most students become better writers? Select all that apply. - Students need to be explicitly taught how to write.", 
               "Which of the following are true about how most students become better writers? Select all that apply. - Students should  plan out what they’re going to write before beginning to write.", 
               "Which of the following are true about how most students become better writers? Select all that apply. - Students can become good writers by reading complex texts.", 
               "Which of the following are true about how most students become better writers? Select all that apply. - Students should have isolated grammar lessons so that they can apply grammar rules in their writing.", 
               "Which of the following are true about how most students become better writers? Select all that apply. - I’m not sure", 
               "All of the following are effective ways a teacher can help students write a stronger sentence EXCEPT:"),
  coding = c("Students need to be explicitly taught how to write.",
             "Students should  plan out what they’re going to write before beginning to write.",
             "incorrect",
             "incorrect",
             "incorrect",
             "Identify incorrect uses of punctuation and correct them."))

ela_guidebooks_diverse_learners_vocabulary_percent <- purrr::map2_df(ela_guidebooks_diverse_learners_vocabulary_correct$question, 
                                                                  ela_guidebooks_diverse_learners_vocabulary_correct$coding, ~ TeachingLab::score_question(data = ela_guidebooks_diverse_learners_vocabulary, 
                                                                                                                                                        question = .x,
                                                                                                                                                        coding = .y,
                                                                                                                                                        grouping = "Please select your site (district, parish, network, or school)"))
```


```{r}
#### Making Survey 11 ELA EL: HQIM & Enrichment ####
# ela_hqim_enrichment <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/ELAHQIM&Enrichment.rds"))
ela_hqim_enrichment <- readr::read_rds("data/ELAHQIM&Enrichment.rds")

ela_hqim_enrichment_correct <- tibble::tibble(
  question = c("Which of the following statements describes gifted learners?", 
               "Which of the following statements describe the Depth and Complexity framework? Select all that apply. - The Depth and Complexity Framework applies specifically to the content area of ELA.", 
               "Which of the following statements describe the Depth and Complexity framework? Select all that apply. - Sequencing the layers of Depth and Complexity to support key standards yields the highest-impact enrichment.", 
               "Which of the following statements describe the Depth and Complexity framework? Select all that apply. - The Depth and Complexity Framework is a differentiation tool that can raise the thinking level for all students.", 
               "Which of the following statements describe the Depth and Complexity framework? Select all that apply. - Teachers should attend to all aspects and layers of the Depth and Complexity framework in any given instructional unit to ensure the highest leverage enrichment experience for students.", 
               "The Multi-Tiered System of Support (MTSS) is a framework that:"),
  coding = c("Gifted learners have special needs in the classroom that fall into these categories: Cognitive, Creative, Affective, Behavioral.",
             "incorrect",
             "Sequencing the layers of Depth and Complexity to support key standards yields the highest-impact enrichment.",
             "The Depth and Complexity Framework is a differentiation tool that can raise the thinking level for all students.",
             "incorrect",
             "Includes universal screening of all students, multiple tiers of instruction and support services, and integrated data collection and assessment systems to inform decisions at each tier of instruction"
))

ela_hqim_enrichment_percent <- purrr::map2_df(ela_hqim_enrichment_correct$question,
                                              ela_hqim_enrichment_correct$coding, ~ 
                                                TeachingLab::score_question(data = ela_hqim_enrichment, 
                                                                            question = .x,
                                                                            coding = .y,
                                                                            grouping = "Please select your site (district, parish, network, or school)"))
```

## Math

```{r}
#### Making Survey 12 Math: Accelerating Learning ####
#### Not complete as of 10-29-31, will need updating on questions, answers ####
# math_accelerating_learning <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/MathAcceleratingLearning.rds"))
math_accelerating_learning <- readr::read_rds("data/MathAcceleratingLearning.rds")

math_accelerating_learning_correct <- tibble::tibble(
  question = c("Which of the following statements describes gifted learners?", 
               "Which of the following statements describe the Depth and Complexity framework? Select all that apply. - The Depth and Complexity Framework applies specifically to the content area of ELA.", 
               "Which of the following statements describe the Depth and Complexity framework? Select all that apply. - Sequencing the layers of Depth and Complexity to support key standards yields the highest-impact enrichment.", 
               "Which of the following statements describe the Depth and Complexity framework? Select all that apply. - The Depth and Complexity Framework is a differentiation tool that can raise the thinking level for all students.", 
               "Which of the following statements describe the Depth and Complexity framework? Select all that apply. - Teachers should attend to all aspects and layers of the Depth and Complexity framework in any given instructional unit to ensure the highest leverage enrichment experience for students.", 
               "The Multi-Tiered System of Support (MTSS) is a framework that:"),
  coding = c("Gifted learners have special needs in the classroom that fall into these categories: Cognitive, Creative, Affective, Behavioral.",
             "incorrect",
             "Sequencing the layers of Depth and Complexity to support key standards yields the highest-impact enrichment.",
             "The Depth and Complexity Framework is a differentiation tool that can raise the thinking level for all students.",
             "incorrect",
             "Includes universal screening of all students, multiple tiers of instruction and support services, and integrated data collection and assessment systems to inform decisions at each tier of instruction"
))

math_accelerating_learning_percent <- purrr::map2_df(math_accelerating_learning_correct$question,
                                              math_accelerating_learning_correct$coding, ~ 
                                                TeachingLab::score_question(data = math_accelerating_learning, 
                                                                            question = .x,
                                                                            coding = .y,
                                                                            grouping = "Please select your site (district, parish, network, or school)"))
```

```{r}
#### Making Survey 13 Math: Bootcamp ####
# math_bootcamp <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/MathBootcamp.rds"))
math_bootcamp <- readr::read_rds("data/MathBootcamp.rds")

math_bootcamp_correct <- tibble::tibble(
  question = c("Which of the following statements describe math instructional shifts associated with college-and-career readiness standards? Select all that apply. - Going deeper into fewer math topics.", 
              "Which of the following statements describe math instructional shifts associated with college-and-career readiness standards? Select all that apply. - Making connections between math topics across grades.", 
              "Which of the following statements describe math instructional shifts associated with college-and-career readiness standards? Select all that apply. - Prioritizing conceptual understanding over procedural skills.", 
              "Which of the following statements describe math instructional shifts associated with college-and-career readiness standards? Select all that apply. - Creating opportunities for students to work on math skills above their grade-level.", 
              "Which of the following statements are true about the research into types of math instruction? Select all that apply. - Unguided problem solving lessons are the least effective type of math lesson.", 
              "Which of the following statements are true about the research into types of math instruction? Select all that apply. - Building deep understanding with fewer math topics is more effective than covering a broader range of math topics.", 
              "Which of the following statements are true about the research into types of math instruction? Select all that apply. - Math instruction that covers more math topics leads to better student performance on assessments.", 
              "Which of the following statements are true about the research into types of math instruction? Select all that apply. - Direct instruction (I do, We do, You do) is the most effective type of math instruction.", 
              "Equitable instruction in math includes which of the following?", 
              "Which of the following statements are true about the principles behind the Mathematical Language Routines? Select all that apply. - Students do not need to understand English completely before they can start making sense of math instruction in English.", 
              "Which of the following statements are true about the principles behind the Mathematical Language Routines? Select all that apply. - An appropriate scaffold for language development is to allow students to make charts, diagrams, and other visual representations of their understanding.", 
              "Which of the following statements are true about the principles behind the Mathematical Language Routines? Select all that apply. - Students who are not proficient in academic English should work with simplified math tasks until they develop stronger language skills.", 
              "Which of the following statements are true about the principles behind the Mathematical Language Routines? Select all that apply. - To demonstrate their mathematical knowledge, students must be able to use formal definitions and vocabulary accurately."),
  coding = c("Going deeper into fewer math topics.", 
             "Making connections between math topics across grades.",
             "incorrect",
             "incorrect",
             "Unguided problem solving lessons are the least effective type of math lesson.",
             "Building deep understanding with fewer math topics is more effective than covering a broader range of math topics.",
             "incorrect",
             "incorrect",
             "Creating opportunities for students to practice saying out loud how they solved for a problem.",
             "Students do not need to understand English completely before they can start making sense of math instruction in English.",
             "An appropriate scaffold for language development is to allow students to make charts, diagrams, and other visual representations of their understanding.",
             "incorrect",
             "incorrect"
))

math_bootcamp_percent <- purrr::map2_df(math_bootcamp_correct$question,
                                              math_bootcamp_correct$coding, ~ 
                                                TeachingLab::score_question(data = math_bootcamp, 
                                                                            question = .x,
                                                                            coding = .y,
                                                                            grouping = "Please select your site (district, parish, network, or school)"))
```

```{r}
#### Making Survey 14 Math: Cycle of Inquiry I - Eliciting Student Thinking ####
#### THIS ONE HAS TO BE SPECIALIZED SINCE IT IS DIFFERENT #####
# math_cycle_inquiry_1_eic <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/MathCycleofInquiryI-ElicitingStudentThinking.rds"))
math_cycle_inquiry_1_eic <- readr::read_rds("data/MathCycleofInquiryI-ElicitingStudentThinking.rds")

math_cycle_inquiry_1_eic_correct <- tibble::tibble(
  question = c("Which of the following statements describe math instructional shifts associated with college-and-career readiness standards? Select all that apply. - Going deeper into fewer math topics.", 
              "Which of the following statements describe math instructional shifts associated with college-and-career readiness standards? Select all that apply. - Making connections between math topics across grades.", 
              "Which of the following statements describe math instructional shifts associated with college-and-career readiness standards? Select all that apply. - Prioritizing conceptual understanding over procedural skills.", 
              "Which of the following statements describe math instructional shifts associated with college-and-career readiness standards? Select all that apply. - Creating opportunities for students to work on math skills above their grade-level.", 
              "Which of the following statements are true about the research into types of math instruction? Select all that apply. - Unguided problem solving lessons are the least effective type of math lesson.", 
              "Which of the following statements are true about the research into types of math instruction? Select all that apply. - Building deep understanding with fewer math topics is more effective than covering a broader range of math topics.", 
              "Which of the following statements are true about the research into types of math instruction? Select all that apply. - Math instruction that covers more math topics leads to better student performance on assessments.", 
              "Which of the following statements are true about the research into types of math instruction? Select all that apply. - Direct instruction (I do, We do, You do) is the most effective type of math instruction.", 
              "Equitable instruction in math includes which of the following?", 
              "Which of the following statements are true about the principles behind the Mathematical Language Routines? Select all that apply. - Students do not need to understand English completely before they can start making sense of math instruction in English.", 
              "Which of the following statements are true about the principles behind the Mathematical Language Routines? Select all that apply. - An appropriate scaffold for language development is to allow students to make charts, diagrams, and other visual representations of their understanding.", 
              "Which of the following statements are true about the principles behind the Mathematical Language Routines? Select all that apply. - Students who are not proficient in academic English should work with simplified math tasks until they develop stronger language skills.", 
              "Which of the following statements are true about the principles behind the Mathematical Language Routines? Select all that apply. - To demonstrate their mathematical knowledge, students must be able to use formal definitions and vocabulary accurately."),
  coding = c("Going deeper into fewer math topics.", 
             "Making connections between math topics across grades.",
             "incorrect",
             "incorrect",
             "Unguided problem solving lessons are the least effective type of math lesson.",
             "Building deep understanding with fewer math topics is more effective than covering a broader range of math topics.",
             "incorrect",
             "incorrect",
             "Creating opportunities for students to practice saying out loud how they solved for a problem.",
             "Students do not need to understand English completely before they can start making sense of math instruction in English.",
             "An appropriate scaffold for language development is to allow students to make charts, diagrams, and other visual representations of their understanding.",
             "incorrect",
             "incorrect"
))

math_cycle_inquiry_1_eic_percent <- purrr::map2_df(math_cycle_inquiry_1_eic_correct$question,
                                              math_cycle_inquiry_1_eic_correct$coding, ~ 
                                                TeachingLab::score_question(data = math_cycle_inquiry_1_eic, 
                                                                            question = .x,
                                                                            coding = .y,
                                                                            grouping = "Please select your site (district, parish, network, or school)"))
```

## Math

```{r}
#### Making Survey 15 Math: Cycle of Inquiry V- Sequencing and Connecting Representations ####
# math_cycle_inquiry_5_scr <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/MathCycleofInquiryV-SequencingandConnectingRepresentations.rds"))
math_cycle_inquiry_5_scr <- readr::read_rds("data/MathCycleofInquiryV-SequencingandConnectingRepresentations.rds")

math_cycle_inquiry_5_scr_correct <- tibble::tibble(
  question = c("Which order represents the general progression in a mathematics discussion using the Five Practices?", 
              "Which of the following best summarizes the purpose of the Five Practices for Orchestrating Mathematics Discussions?", 
              "Which of the following statements are always true about the Five Practices for Orchestrating Mathematics Discussions? Select all that apply. - We show student work one at a time during Sequencing.", 
              "Which of the following statements are always true about the Five Practices for Orchestrating Mathematics Discussions? Select all that apply. - We lead students to a pre-planned mathematical idea during Connecting.", 
              "Which of the following statements are always true about the Five Practices for Orchestrating Mathematics Discussions? Select all that apply. - We use student data to inform our planning during Anticipation.", 
              "Which of the following statements are always true about the Five Practices for Orchestrating Mathematics Discussions? Select all that apply. - We begin thinking about student misconceptions during Monitoring.", 
              "Which of the following statements are always true about the Five Practices for Orchestrating Mathematics Discussions? Select all that apply. - We can gather a variety of student work during Selecting.", 
              "Which of the following statements are always true about the Five Practices for Orchestrating Mathematics Discussions? Select all that apply. - I’m not sure", 
              "A lesson representative of “Leveraging multiple mathematical competencies” does which of the following? Select all that apply. - Presents tasks that offer multiple entry points", 
              "A lesson representative of “Leveraging multiple mathematical competencies” does which of the following? Select all that apply. - Requires students to show mastery of skills prior to engaging in more complex problem solving", 
              "A lesson representative of “Leveraging multiple mathematical competencies” does which of the following? Select all that apply. - Gives ambivalent value to flexibility, reasoning, and persistence", 
              "A lesson representative of “Leveraging multiple mathematical competencies” does which of the following? Select all that apply. - Structures collaboration to use varying math knowledge and skills to solve complex problems", 
              "A lesson representative of “Leveraging multiple mathematical competencies” does which of the following? Select all that apply. - I’m not sure.", 
              "Which question best represents what teachers would ask themselves as they plan a lesson to ”Leveraging Multiple Math Competencies”?"),
  coding = c("Anticipate, Monitor, Select, Sequence, Connect",
             "Emphasize the importance of planning to create an engaging mathematical discussion",
             "incorrect",
             "We lead students to a pre-planned mathematical idea during Connecting.",
             "We use student data to inform our planning during Anticipation.",
             "incorrect",
             "We can gather a variety of student work during Selecting.",
             "incorrect",
             "Presents tasks that offer multiple entry points",
             "incorrect",
             "incorrect",
             "Structures collaboration to use varying math knowledge and skills to solve complex problems",
             "incorrect",
             "How do I identify and support mathematical contributions from students with different strengths and levels of confidence?"))

math_cycle_inquiry_5_scr_percent <- purrr::map2_df(math_cycle_inquiry_5_scr_correct$question,
                                              math_cycle_inquiry_5_scr_correct$coding, ~ 
                                                TeachingLab::score_question(data = math_cycle_inquiry_5_scr, 
                                                                            question = .x,
                                                                            coding = .y,
                                                                            grouping = "Please select your site (district, parish, network, or school)"))
```


```{r}
#### Making Survey 16 ELA: School Leaders ####
# ela_school_leaders <- readr::read_rds(here::here("Dashboards/KnowledgeAssessments/data/SchoolLeadersELA.rds"))
ela_school_leaders <- readr::read_rds("data/SchoolLeadersELA.rds")

ela_school_leaders_correct <- tibble::tibble(
  question = c("Which of the following are literacy instructional shifts? Select all that apply. - Regular practice with complex texts and their academic language.", 
              "Which of the following are literacy instructional shifts? Select all that apply. - Building knowledge through content-rich non-fiction.", 
              "Which of the following are literacy instructional shifts? Select all that apply. - Equal balance of text-based writing and writing from personal experiences. ", 
              "Which of the following are literacy instructional shifts? Select all that apply. - Regular opportunities for direct instruction on reading comprehension strategies.", 
              "Which of the following are literacy instructional shifts? Select all that apply. - I'm not sure.", 
              "Which of the following are examples of text-specific questions? Select all that apply. - What can you infer from Dr. King’s letter about the letter that he received?", 
              "Which of the following are examples of text-specific questions? Select all that apply. - In “The Lion, the Witch, and the Wardrobe”, how and why does Edmund change?", 
              "Which of the following are examples of text-specific questions? Select all that apply. - In “Casey at the Bat,” Casey strikes out. Describe a time when you failed at something.", 
              "Which of the following are examples of text-specific questions? Select all that apply. - In “Letter from a Birmingham Jail,” Dr. King discusses nonviolent protests. Write about a time when you wanted to fight against something that you felt was unfair.", 
              "Which of the following statements are true about the purpose of the Instructional Practice Guide (IPG)? Select all that apply. - It focuses on observations aligned to the ELA and literacy instructional shifts", 
              "Which of the following statements are true about the purpose of the Instructional Practice Guide (IPG)? Select all that apply. - It is a coaching tool that supports identifying equitable literacy practices.", 
              "Which of the following statements are true about the purpose of the Instructional Practice Guide (IPG)? Select all that apply. - It can be used to diagnose unfinished learning needs of students.", 
              "Which of the following statements are true about the purpose of the Instructional Practice Guide (IPG)? Select all that apply. - It is a tool that can be used to determine teacher effectiveness in formal observations.", 
              "Which of the following statements are true about the purpose of the Instructional Practice Guide (IPG)? Select all that apply. - I'm not sure.", 
              "Which of the following describes effective feedback to a teacher following an observation? Select all that apply. - The feedback is focused on teacher moves such as the questions the teachers posed as students read the text.", 
              "Which of the following describes effective feedback to a teacher following an observation? Select all that apply. - The interaction includes role-playing for the teacher to practice a new strategy which directly addresses a challenge from the observation.", 
              "Which of the following describes effective feedback to a teacher following an observation? Select all that apply. - The feedback makes clear the supervisor’s opinion about the teacher’s instruction pedagogy.", 
              "Which of the following describes effective feedback to a teacher following an observation? Select all that apply. - The feedback is delivered via email so that the teacher can respond in writing.", 
              "Which of the following describes effective feedback to a teacher following an observation? Select all that apply. - I'm not sure."),
  coding = c("Regular practice with complex texts and their academic language.",
             "Building knowledge through content-rich non-fiction.",
             "incorrect",
             "incorrect",
             "incorrect",
             "What can you infer from Dr. King’s letter about the letter that he received?",
             "In “The Lion, the Witch, and the Wardrobe”, how and why does Edmund change?",
             "incorrect",
             "incorrect",
             "It focuses on observations aligned to the ELA and literacy instructional shifts",
             "It is a coaching tool that supports identifying equitable literacy practices.",
             "incorrect",
             "incorrect",
             "incorrect",
             "The feedback is focused on teacher moves such as the questions the teachers posed as students read the text.",
             "The interaction includes role-playing for the teacher to practice a new strategy which directly addresses a challenge from the observation.",
             "incorrect",
             "incorrect",
             "incorrect"

))

ela_school_leaders_percent <- purrr::map2_df(ela_school_leaders_correct$question,
                                              ela_school_leaders_correct$coding, ~ 
                                                TeachingLab::score_question(data = ela_school_leaders, 
                                                                            question = .x,
                                                                            coding = .y,
                                                                            grouping = "Please select your site (district, parish, network, or school)"))
```




