---
title: "Race and Culture Survey Analysis"
author: "Duncan Gates"
date: "7/13/2021"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
library(tidyverse)
library(here)
library(ggtext)
library(systemfonts)
devtools::load_all()
library(TeachingLab)
library(googlesheets4)
library(janitor)
```

# Read in Data

```{r}
march2019 <- read_sheet("https://docs.google.com/spreadsheets/d/1q9jlAVS_iKUdgLWT9TAhDZ5b2RUhyei0XxwNjDHwPkM/edit#gid=160629191", sheet = "Form Responses 1", skip = 1)
july2019 <- read_sheet("https://docs.google.com/spreadsheets/d/1GaGYf0RtPNmzOGFM1XB27H5eyP4T9lMCMH3MTjAUupI/edit#gid=674715077", sheet = "Form Responses 1", skip = 1) %>%
  select(-c(47:49))
february2020 <- read_sheet("https://docs.google.com/spreadsheets/d/19jbdok4Lh7iOf-UlJFA_sXC80a8fmQ_lIgxiEJhhjxs/edit#gid=394003930", sheet = "Form Responses 1", skip = 1)
november2020 <- read_sheet("https://docs.google.com/spreadsheets/d/1zLUuycxMKxMPZ-VoFzwCLgpY2qfKcgyimUdrww2ehAQ/edit#gid=1438011169", sheet = "Form Responses 1", skip = 1)
```

# Cleaning with Janitor

```{r}
compare_cols <- compare_df_cols(july2019, march2019, february2020, november2020)
```

# Rename data for join

```{r}
column_rename = c("Are you a full-time team member or Fellow at Teaching Lab?" = "What is your role?",
  "Are you a full-time team member or Fellow at Teaching Lab?" = "What is your role?...2",
  "Are you a full-time team member or Fellow at Teaching Lab?" = "Are you a full-time team member or Fellow at Teaching Lab?...2",
  "Are you a full-time team member or Fellow at Teaching Lab?" = "Are you a full-time team member or Fellow at Teaching Lab?...34",
  "Are you a people manager at Teaching Lab?" = "Are you currently a Chief or Director at Teaching Lab?...4",
  "Are you a people manager at Teaching Lab?" = "Are you currently a Director, Managing Director, or Chief at Teaching Lab?...5",
  "Are you a people manager at Teaching Lab?" = "Are you currently a Director, Managing Director, or Chief at Teaching Lab?...51",
  "Are you a people manager at Teaching Lab?" = "Are you part of the Leadership Team at Teaching Lab?",
  "Do you know any candidates who would be great for roles at Teaching Lab? If so, please share names, contact information, and how you think they could contribute." = "Do you know any prospects who would be great for roles at Teaching Lab? If so, please share names, contact information, and areas of professional interest.",
  "How do you identify racially or ethnically?" = "How do you identify racially or ethnically?...3",
  "How do you identify racially or ethnically?" = "How do you identify racially or ethnically?...50",
  "If you have comments or feedback about the statements above, please share with us" = "If you have comments or feedback about the statements above, please share with us....35",
  "If you have comments or feedback about the statements above, please share with us" = "If you have comments or feedback about the statements above, please share with us....43")
```


# Join Data

```{r}
left_join(march2019, july2019, by = c(""))
```





