---
title: "Graph Maker"
author: "Duncan Gates"
date: "5/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(TeachingLab)
library(tidyverse)
library(ggtext)
```

# Segment Graphs

## Graph 4: Educators' Average Scores on Content and Pedagogical Content Knowledge in Fall and Spring

```{r}
# graph4 <- data3 %>%
#   slice(-6) %>%
#   select(1:3) %>%
#   pivot_longer(!rowname, names_to = "prepost", values_to = "mean_score") %>%
#   rename(Question = rowname) %>%
#   mutate(Question = str_to_title(Question)) %>%
#   mutate(Question = str_replace_all(Question, "With", "with"))

graph4 <- structure(list(Question = c("Overall Score", "Overall Score", 
"Math Instructional Shifts", "Math Instructional Shifts", "Equitable Math Instruction", 
"Equitable Math Instruction", "Supporting Students with<br>Unfinished Learning", 
"Supporting Students with<br>Unfinished Learning", "Effective Teaching Practices", 
"Effective Teaching Practices"), prepost = c("Average score\nDiagnostic", 
"Average score\nFollow-up", "Average score\nDiagnostic", "Average score\nFollow-up", 
"Average score\nDiagnostic", "Average score\nFollow-up", "Average score\nDiagnostic", 
"Average score\nFollow-up", "Average score\nDiagnostic", "Average score\nFollow-up"
), mean_score = c(54, 56, 44, 42, 61, 65, 61, 70, 49, 47)), row.names = c(NA, 
-10L), class = c("tbl_df", "tbl", "data.frame"))

graph4 <- graph4 %>% mutate(Question = str_replace_all(Question, "Supporting Students with Unfinished Learning", "Supporting Students with<br>Unfinished Learning"))

graph4$Question <- factor(graph4$Question, levels = c("Effective Teaching Practices", "Supporting Students with<br>Unfinished Learning", "Equitable Math Instruction", 
                                               "Math Instructional Shifts", "Overall Score"))

graph4_segments <- tibble(
  x = graph4 %>% filter(str_detect(prepost, "Follow")) %>% pull(mean_score),
  xend = graph4 %>% filter(str_detect(prepost, "Diagnostic")) %>% pull(mean_score),
  y = graph4 %>% filter(str_detect(prepost, "Follow")) %>% pull(Question),
  yend = graph4 %>% filter(str_detect(prepost, "Diagnostic")) %>% pull(Question),
  fall_text = c(58, 40, 66, 70, 45),
  spring_text = c(52, 46, 60, 61, 51)
)

ggplot() +
  geom_point(data = graph4, mapping = aes(color = prepost, x = mean_score, y = Question, size = mean_score)) +
  geom_segment(data = graph4_segments, mapping = aes(x = x, xend = xend, y = y, yend = yend, alpha = 0.7), color = "black", size = 0.3, arrow = arrow(length = unit(0.1, "inches"))) +
  geom_richtext(data = graph4_segments, fill = NA, label.color = NA,
                aes(x = fall_text, y = y, label = paste0(x, "%")), 
                color = "#ff7b43", vjust = -0.5, size = 4.85) +
  geom_richtext(data = graph4_segments, fill = NA, label.color = NA,
                aes(x = spring_text, y = y, label = paste0(xend, "%")), 
                color = "#00acf0", vjust = -0.5, size = 4.85) +
  scale_color_manual(values = rev(c("#ff7b43", "#00acf0"))) +
  scale_x_continuous(labels = scales::percent_format(scale = 1), breaks = scales::pretty_breaks(n = 5),
                     limits = c(0, 100)) +
  labs(x = NULL, y = NULL,
       title = "Educators' Average Scores on Math and Pedagogical<br>Content Knowledge in <span style = 'color:#ff7b43;'>Diagnostic</span> and <span style = 'color:#00acf0;'>Follow-up</span> Surveys") +
  theme_bw() +
  theme(panel.border = element_blank(),
        legend.position = "none",
        plot.title = element_markdown(hjust = 0.5, family = "Calibri", size = 20, lineheight = 1.15),
        text = element_text(family = "Calibri"),
        axis.text.y = element_markdown(hjust = 0.5, lineheight = 1.1, size = 14),
        axis.text.x = element_markdown(size = 14)) +
    ggsave(here("Images/Legacy Graphs/Graph 4.png"), width = 12, height = 8)
```
## Graph 3

```{r}
# graph3 <- data2 %>%
#     select(1:3) %>%
#     slice(-9) %>%
#     pivot_longer(!rowname, names_to = "prepost", values_to = "mean_score") %>%
#     rename(Question = rowname) %>%
#     mutate(Question = str_to_title(Question)) %>%
#     mutate(Question = str_replace_all(Question, "With", "with"))

graph3 <- structure(list(Question = c("Overall Score", "Overall Score", 
"Ela Early Literacy", "Ela Early Literacy", "Ela Instructional Shifts", 
"Ela Instructional Shifts", "Fluency", "Fluency", "Text Complexity", 
"Text Complexity", "Evidence & Close Reading", "Evidence & Close Reading", 
"Building Knowledge", "Building Knowledge", "Supporting Students with Unfinished Learning", 
"Supporting Students with Unfinished Learning"), prepost = c("Average score\nDiagnostic", 
"Average score \nFollow-up", "Average score\nDiagnostic", "Average score \nFollow-up", 
"Average score\nDiagnostic", "Average score \nFollow-up", "Average score\nDiagnostic", 
"Average score \nFollow-up", "Average score\nDiagnostic", "Average score \nFollow-up", 
"Average score\nDiagnostic", "Average score \nFollow-up", "Average score\nDiagnostic", 
"Average score \nFollow-up", "Average score\nDiagnostic", "Average score \nFollow-up"
), mean_score = c(45, 73, 39, NA, 32, 8, 51, 75, 38, 80, 58, 
75, 40, 88, 59, 70)), row.names = c(NA, -16L), class = c("tbl_df", 
"tbl", "data.frame"))
  
graph3 <- graph3 %>% mutate(Question = str_replace_all(str_wrap(Question, 20), "\n", "<br>"))
  
graph3$Question <- factor(graph3$Question, levels = rev(c("Overall Score", "Ela Early Literacy", "Ela Instructional<br>Shifts", 
"Fluency", "Text Complexity", "Evidence & Close<br>Reading", 
"Building Knowledge", "Supporting Students<br>with Unfinished<br>Learning"
)))
  
graph3_segments <- tibble(
    xend = graph3 %>% filter(str_detect(prepost, "Follow")) %>% pull(mean_score),
    x = graph3 %>% filter(str_detect(prepost, "Diagnostic")) %>% pull(mean_score),
    y = graph3 %>% filter(str_detect(prepost, "Follow")) %>% pull(Question),
    yend = graph3 %>% filter(str_detect(prepost, "Diagnostic")) %>% pull(Question),
    fall_text = x,
    spring_text = xend
  )
  
ggplot() +
    geom_point(data = graph3, mapping = aes(color = prepost, x = mean_score, y = Question, size = mean_score)) +
    geom_segment(data = graph3_segments, mapping = aes(x = x, xend = xend, y = y, yend = yend, alpha = 0.7), color = "black", size = 0.3, arrow = arrow(length = unit(0.1, "inches"))) +
    geom_richtext(data = graph3_segments, fill = NA, label.color = NA,
                  aes(x = fall_text, y = y, label = paste0(x, "%")), 
                  color = "#ff7b43", vjust = -0.5, size = 4.85) +
    geom_richtext(data = graph3_segments, fill = NA, label.color = NA,
                  aes(x = spring_text, y = y, label = paste0(xend, "%")), 
                  color = "#00acf0", vjust = -0.5, size = 4.85) +
    scale_color_manual(values = rev(c("#00acf0", "#ff7b43"))) +
    scale_x_continuous(labels = scales::percent_format(scale = 1), breaks = scales::pretty_breaks(n = 5),
                       limits = c(0, 100)) +
    labs(x = NULL, y = NULL,
         title = "Educators' Average Scores on ELA Content and Pedagogical Content Knowledge in the <br> <span style = 'color:#ff7b43;'>Diagnostic</span> and <span style = 'color:#00acf0;'>Follow-up<span> Surveys") +
    theme_bw() +
    theme(panel.border = element_blank(),
          legend.position = "none",
          plot.title = element_markdown(hjust = 0.5, family = "Calibri", size = 20, lineheight = 1.15),
          text = element_text(family = "Calibri"),
          axis.text.y = element_markdown(hjust = 0.5, lineheight = 1.1, size = 14),
          axis.text.x = element_markdown(size = 14)) +
      ggsave(here("Images/Legacy Graphs/Graph 3.png"), width = 12, height = 8)
```

## Graph 2

```{r}
# graph2 <- data1 %>%
#     select(1:3) %>%
#     slice(-6) %>%
#     pivot_longer(!rowname, names_to = "prepost", values_to = "mean_score") %>%
#     rename(Question = rowname) %>%
#     mutate(Question = str_to_title(Question)) %>%
#     mutate(Question = str_replace_all(Question, "With", "with"))

graph2 <- structure(list(Question = c("Overall Score", "Overall Score", 
"Trust In Fellow Teachers", "Trust In Fellow Teachers", "Connectedness To Fellow Teachers", 
"Connectedness To Fellow Teachers", "Have Influence Over Professional Learning", 
"Have Influence Over Professional Learning", "I Am Confident That I Am Implementing The Curriculum In A Way That Maximizes Positive Impact For Student Learning", 
"I Am Confident That I Am Implementing The Curriculum In A Way That Maximizes Positive Impact For Student Learning"
), prepost = c("% of educators who agreed or strongly agreed\nDiagnostic", 
"% of educators who agreed or strongly agreed\nFollow-up", "% of educators who agreed or strongly agreed\nDiagnostic", 
"% of educators who agreed or strongly agreed\nFollow-up", "% of educators who agreed or strongly agreed\nDiagnostic", 
"% of educators who agreed or strongly agreed\nFollow-up", "% of educators who agreed or strongly agreed\nDiagnostic", 
"% of educators who agreed or strongly agreed\nFollow-up", "% of educators who agreed or strongly agreed\nDiagnostic", 
"% of educators who agreed or strongly agreed\nFollow-up"), mean_score = c(66, 
65, 92, 77, 84, 92, 32, 23, 55, 69)), row.names = c(NA, -10L), class = c("tbl_df", 
"tbl", "data.frame"))
  
graph2 <- graph2 %>% mutate(Question = str_replace_all(str_wrap(Question, 20), "\n", "<br>"))
  
graph2$Question <- factor(graph2$Question, levels = rev(c("Overall Score", "Trust In Fellow<br>Teachers", "Connectedness To<br>Fellow Teachers", 
"Have Influence<br>Over Professional<br>Learning", "I Am Confident That<br>I Am Implementing<br>The Curriculum In A<br>Way That Maximizes<br>Positive Impact For<br>Student Learning"
)))
  
graph2_segments <- tibble(
    xend = graph2 %>% filter(str_detect(prepost, "Follow")) %>% pull(mean_score),
    x = graph2 %>% filter(str_detect(prepost, "Diagnostic")) %>% pull(mean_score),
    y = graph2 %>% filter(str_detect(prepost, "Follow")) %>% pull(Question),
    yend = graph2 %>% filter(str_detect(prepost, "Diagnostic")) %>% pull(Question),
    fall_text = c(68, 92, 84, 32, 55),
    spring_text = c(63, 77, 92, 23, 69)
  )
  
ggplot() +
    geom_point(data = graph2, mapping = aes(color = prepost, x = mean_score, y = Question, size = mean_score)) +
    geom_segment(data = graph2_segments, mapping = aes(x = x, xend = xend, y = y, yend = yend, alpha = 0.7), color = "black", size = 0.3, arrow = arrow(length = unit(0.1, "inches"))) +
    geom_richtext(data = graph2_segments, fill = NA, label.color = NA,
                  aes(x = fall_text, y = y, label = paste0(x, "%")), 
                  color = "#ff7b43", vjust = -0.5, size = 4.85) +
    geom_richtext(data = graph2_segments, fill = NA, label.color = NA,
                  aes(x = spring_text, y = y, label = paste0(xend, "%")), 
                  color = "#00acf0", vjust = -0.5, size = 4.85) +
    scale_color_manual(values = rev(c("#00acf0", "#ff7b43"))) +
    scale_x_continuous(labels = scales::percent_format(scale = 1), breaks = scales::pretty_breaks(n = 5),
                       limits = c(0, 100)) +
    labs(x = NULL, y = NULL,
         title = "Change in the Percent of Educators with Positive Perceptions of<br>School Culture and Climate from <span style = 'color:#ff7b43;'>Diagnostic</span> to <span style = 'color:#00acf0;'>Follow-up<span> Survey") +
    theme_bw() +
    theme(panel.border = element_blank(),
          legend.position = "none",
          plot.title = element_markdown(hjust = 0.5, family = "Calibri", size = 20, lineheight = 1.15),
          text = element_text(family = "Calibri"),
          axis.text.y = element_markdown(hjust = 0.5, lineheight = 1.1, size = 14),
          axis.text.x = element_markdown(size = 14)) +
      ggsave(here("Images/Legacy Graphs/Graph 2.png"), width = 12, height = 8)
```

## Graph 1

```{r}
# graph1 <- data4 %>%
#     select(1:3) %>%
#     slice(-6) %>%
#     pivot_longer(!rowname, names_to = "prepost", values_to = "mean_score") %>%
#     rename(Question = rowname) %>%
#     mutate(Question = str_to_title(Question)) %>%
#     mutate(Question = str_replace_all(Question, "With", "with"))

graph1 <- structure(list(Question = c("Overall", "Overall", "Race & Ethnicity", 
"Race & Ethnicity", "Growth Mindsets", "Growth Mindsets", "High Expectations", 
"High Expectations", "Accountability", "Accountability"), prepost = c("Diagnostic\nOverall", 
"Follow up\nOverall", "Diagnostic\nOverall", "Follow up\nOverall", 
"Diagnostic\nOverall", "Follow up\nOverall", "Diagnostic\nOverall", 
"Follow up\nOverall", "Diagnostic\nOverall", "Follow up\nOverall"
), mean_score = c(75, 73, 52, 61, 96, 82, 56, 58, 97, 92)), row.names = c(NA, 
-10L), class = c("tbl_df", "tbl", "data.frame"))
  
graph1 <- graph1 %>% mutate(Question = str_replace_all(str_wrap(Question, 20), "\n", "<br>"))
  
graph1$Question <- factor(graph1$Question, levels = rev(c("Overall", "Race & Ethnicity", "Growth Mindsets", "High Expectations", 
"Accountability")))
  
graph1_segments <- tibble(
    xend = graph1 %>% filter(str_detect(prepost, "Follow")) %>% pull(mean_score),
    x = graph1 %>% filter(str_detect(prepost, "Diagnostic")) %>% pull(mean_score),
    y = graph1 %>% filter(str_detect(prepost, "Follow")) %>% pull(Question),
    yend = graph1 %>% filter(str_detect(prepost, "Diagnostic")) %>% pull(Question),
    fall_text = c(77, 52, 96, 54, 97),
    spring_text = c(71, 61, 82, 60, 91)
  )
  
ggplot() +
    geom_point(data = graph1, mapping = aes(color = prepost, x = mean_score, y = Question, size = mean_score)) +
    geom_segment(data = graph1_segments, mapping = aes(x = x, xend = xend, y = y, yend = yend, alpha = 0.7), color = "black", size = 0.3, arrow = arrow(length = unit(0.1, "inches"))) +
    geom_richtext(data = graph1_segments, fill = NA, label.color = NA,
                  aes(x = fall_text, y = y, label = paste0(x, "%")), 
                  color = "#ff7b43", vjust = -0.5, size = 4.85) +
    geom_richtext(data = graph1_segments, fill = NA, label.color = NA,
                  aes(x = spring_text, y = y, label = paste0(xend, "%")), 
                  color = "#00acf0", vjust = -0.5, size = 4.85) +
    scale_color_manual(values = rev(c("#00acf0", "#ff7b43"))) +
    scale_x_continuous(labels = scales::percent_format(scale = 1), breaks = scales::pretty_breaks(n = 5),
                       limits = c(0, 100)) +
    labs(x = NULL, y = NULL,
         title = "Educators' Average Scores on Mindsets and Beliefs in the <br> <span style = 'color:#ff7b43;'>Diagnostic</span> and <span style = 'color:#00acf0;'>Follow-up<span> Surveys") +
    theme_bw() +
    theme(panel.border = element_blank(),
          legend.position = "none",
          plot.title = element_markdown(hjust = 0.5, family = "Calibri", size = 20, lineheight = 1.15),
          text = element_text(family = "Calibri"),
          axis.text.y = element_markdown(hjust = 0.5, lineheight = 1.1, size = 14),
          axis.text.x = element_markdown(size = 14)) +
      ggsave(here("Images/Legacy Graphs/Graph 1.png"), width = 12, height = 8)
```